"""add public chat privacy and gender to users table

Revision ID: 916ab34c7536
Revises: c807f8502ab8
Create Date: 2026-08-29 03:05:56.547620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916ab34c7536'
down_revision = 'c807f8502ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('show_username_in_public_chat', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_username_in_public_chat')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
